### ISSUE TITLE
how to fix java.lang.NoSuchFieldError: RETURN_BLANK_AS_NULL

### ISSUE THREAD

**Issue by srinivas-varma-oa** [teiid/teiid-embedded-examples#54]
i have run same project in java below error is coming up

10:53:14.337 [Worker2_QueryProcessorQueue2] ERROR org.teiid.CONNECTOR - Connector worker process failed for atomic-request=pcnik6Sg+l5d.0.1.0
java.lang.NoSuchFieldError: RETURN_BLANK_AS_NULL
	at org.teiid.translator.excel.ExcelExecution.projectRow(ExcelExecution.java:230)
	at org.teiid.translator.excel.ExcelExecution.next(ExcelExecution.java:160)
	at org.teiid.dqp.internal.datamgr.ConnectorWorkItem.handleBatch(ConnectorWorkItem.java:428)
	at org.teiid.dqp.internal.datamgr.ConnectorWorkItem.more(ConnectorWorkItem.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.teiid.dqp.internal.datamgr.ConnectorManager$1.invoke(ConnectorManager.java:216)
	at com.sun.proxy.$Proxy18.more(Unknown Source)
	at org.teiid.dqp.internal.process.DataTierTupleSource.getResults(DataTierTupleSource.java:305)
	at org.teiid.dqp.internal.process.DataTierTupleSource$1.call(DataTierTupleSource.java:108)
	at org.teiid.dqp.internal.process.DataTierTupleSource$1.call(DataTierTupleSource.java:104)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.teiid.dqp.internal.process.FutureWork.run(FutureWork.java:61)
	at org.teiid.dqp.internal.process.DQPWorkContext.runInContext(DQPWorkContext.java:280)
	at org.teiid.dqp.internal.process.ThreadReuseExecutor$RunnableWrapper.run(ThreadReuseExecutor.java:115)
	at org.teiid.dqp.internal.process.ThreadReuseExecutor$3.run(ThreadReuseExecutor.java:206)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

**Comment by rareddy** [comment]
That looks like your compile time and runtime dependencies are different versions
